### PR TITLE
Fix onUserDestroy() being called within game loop

### PR DESCRIPTION
**Pull request by baderouaich**
Hello! 
First, thanks a lot for this really cool port to android/ios!
 
As i was trying it on my android device, I tried to log print each callback name to get a grips of when things are called as below:
```cpp
class PGE_Mobile : public olc::PixelGameEngine {
public:
    PGE_Mobile() {
      sAppName = "PGE Mobile Demo";
    }

public:
    bool OnUserCreate() override {
        LOGI("%s", __PRETTY_FUNCTION__);
        return true;
    }

    bool OnUserUpdate(float fElapsedTime) override {
       static float dt = 0.0f; 
       dt += fElapsedTime;
       if(dt >= 1.0f) {
          LOGI("%s", __PRETTY_FUNCTION__);
          dt = 0.0f;
        }
        return true;
    }


    bool OnUserDestroy() override {
        LOGI("%s", __PRETTY_FUNCTION__);
        return true;
    }

    void OnSaveStateRequested() override
    {
      LOGI("%s", __PRETTY_FUNCTION__);
    }

    void OnRestoreStateRequested() override
    {
      LOGI("%s", __PRETTY_FUNCTION__);
    }
};
```

and then the log cat shows calls to OnUserDestroy() every frame:
image

At first I thought it was my phone, tried to restart it and the issue still persists, then had a look at the places OnUserDestroy() is called in [olcPixelGameEngine_Mobile.h](https://github.com/Johnnyg63/OLCPGEMobile_AndroidStudio/blob/master/app/src/main/cpp/olcPixelGameEngine_Mobile.h), then I noticed the [OnUserDestroy() was being called](https://github.com/Johnnyg63/OLCPGEMobile_AndroidStudio/blob/master/app/src/main/cpp/olcPixelGameEngine_Mobile.h#L7265) withing the [while(bAtomActive) {} game loop](https://github.com/Johnnyg63/OLCPGEMobile_AndroidStudio/blob/master/app/src/main/cpp/olcPixelGameEngine_Mobile.h#L7201)

image

So yes, I guess this PR should fix it. Thanks again for your work and have a great day!

### CODE REVIEW

**Comment by baderouaich** [comment]
Also this might have been done on purpose, perhaps the olc Mobile callbacks aren't called in same way as the olc Desktop version, if that was the case please ignore this PR. Thanks!

**Comment by Johnnyg63** [comment]
Hi 👋 Bader!,

Thank you so much for reviewing my code, I really really appreciate the feedback 😊 

Good news the onUserDestory() is meant to be called on each frame, so you the developer always have away of terminating the app should crap go wrong. Which as you know can happen a lot with Android. 

However I do understand where the confusion is occurring, the name of the method suggests it is the phone user destroying the app. The method name comes from the Windows/Linux PGE 2.0 and was reused in Android/iOS so folks could continue to use the same code.

To access phone user events just use the EventManager class built into the engine.

Again thank you so much, there are about 246 developers using this repo, but I hardly ever get any feedback.

Please please come to our discord and let me know what you think please 
https://discord.com/invite/WhwHUMV

Kind regards 

Johnnyg63

**Comment by Johnnyg63** [comment]
Hi Bader....

You are right, the onUserDestory should only be called when the app is been destroyed... shoot, great catch! 

I cannot merge your code yet, I need to check the logic for the OS events first 

Thank you so much for this 

Kind regards 

John

**Comment by baderouaich** [comment]
Hi John,

Thank you for the quick reply! 
You're right, when I saw OnUserDestroy() at first I thought it will be called before the app is terminated since this is the behavior PGE Desktop has so the user will do the cleanup (close files, save state..).

I had no idea an EventManager class exists! very interesting actually I will check that out. Thank you!

By the way I think I am already in the Discord group, I just haven't been active there much, but we could create a Thread in some chat and discuss this matter, actually, it will be better to have a new chat specifically for this repository where everyone can share feedback/issues/projects and other things.

The changes I did in this PR is just inspired from the PGE Desktop version, specifically [here](https://github.com/OneLoneCoder/olcPixelGameEngine/blob/ae284d9220e17405911bd6bf23a7f75c38cc0ba8/olcPixelGameEngine.h#L3861), where there are two while loops, the first level one repeats the main loop if OnUserDestroy() returns false (user denies the termination event for some reason), the second level one is the game loop. 

I agree you should not merge it yet because I have not tested it well, but I'm glad you got the issue now and that's the goal! I hope it will be fixed soon, also I would love to learn and help with that in Discord.

Thank you again for your work and have a good day! see you in Discord!

Bader

**Comment by Johnnyg63** [comment]
Hey Bader

You got the credit for this, your change is in Release 2.2.8, I had to update the iOS version too and hence why I couldn't bring in your code directly from the PR

Kind regards

John

**Pull request closed without merging**
